# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20171108_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorite_song',
            field=models.BooleanField(default=False),
        ),
    ]
